Repository rahulshamkuwar/ChatterSquare, pull requests merged in 2022-11, with the labels that each got.

#29 Added lab10 PDF
  Milestone-Submission/Software Dev Project Info.pdf
Labels: documentation

#32 adding register skeleton
  src/views/pages/register.ejs
Labels: feature

#33 Changed folder structure with config, controllers, routes, services.
  src/config/db.config.js
  src/controllers/loginController.js
  src/controllers/registerController.js
  src/index.js
  src/routes/index.js
  src/routes/login.js
  src/routes/register.js
  src/services/database.js
Labels: enhancement

#35 Added changes to db structure
  src/init_data/create.sql
Labels: enhancement

#44 Added database helper functions
  src/controllers/loginController.js
  src/controllers/registerController.js
  src/init_data/create.sql
  src/package-lock.json
  src/routes/index.js
  src/services/database.js
  src/views/partials/header.ejs
Labels: enhancement

#57 Alert bug
  src/controllers/logoutController.js
  src/controllers/registerController.js
  src/views/partials/alert.ejs
Labels: bug

#56 Register
  .gitignore
  src/views/pages/register.ejs
Labels: feature

#62 fixed bugs with the register validation
  src/controllers/registerController.js
  src/views/pages/register.ejs
Labels: bug

#58 added validation and removed .devcontainer
  .gitignore
  src/views/pages/login.ejs
Labels: enhancement

#67 Change password backend
  src/controllers/loginController.js
  src/controllers/profileController.js
  src/package-lock.json
  src/routes/profile.js
  src/services/database.js
  src/views/pages/profile.ejs
Labels: feature

#72 updated perk details on profile page
  src/views/pages/profile.ejs
Labels: feature

#75 Added change username functionality
  src/controllers/profileController.js
  src/routes/profile.js
  src/views/pages/profile.ejs
Labels: feature

#76 Change profile
  src/controllers/profileController.js
  src/index.js
  src/package-lock.json
  src/routes/profile.js
  src/services/database.js
  src/views/pages/profile.ejs
  src/views/partials/nav-bar.ejs
Labels: feature

#74 Changed alertbox errors so they do not show on empty chats.
  src/controllers/loginController.js
  src/controllers/profileController.js
  src/package-lock.json
  src/package.json
  src/services/chat.js
  src/views/pages/profile.ejs
Labels: bug

#79 Points system
  src/controllers/loginController.js
  src/controllers/profileController.js
  src/init_data/create.sql
  src/package-lock.json
  src/routes/profile.js
  src/services/database.js
  src/views/pages/profile.ejs
Labels: feature

#82 Update README.md
  README.md
Labels: documentation

#77 Square frontend
  src/resources/css/square.css
  src/resources/css/style.css
  src/services/chat.js
  src/views/pages/square.ejs
  src/views/partials/nav-bar.ejs
Labels: feature

#84 Perk display
  src/controllers/loginController.js
  src/init_data/create.sql
  src/resources/css/square.css
  src/resources/css/style.css
  src/services/chat.js
  src/services/database.js
  src/views/pages/profile.ejs
  src/views/pages/square.ejs
Labels: bug, feature

#85 Updated flow so that the web container waits for the db container. Al…
  README.md
  docker-compose.yaml
  src/package-lock.json
  src/package.json
  src/views/pages/login.ejs
  src/views/pages/profile.ejs
  src/views/pages/register.ejs
  src/views/pages/square.ejs
  src/views/partials/header.ejs
  src/wait-for-it.sh
Labels: bug, documentation, enhancement
